/*
 * Copyright (C) 2015 Zhang Rui <bbcallen@gmail.com>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * https://github.com/Bilibili/jni4android
 * This file is automatically generated by jni4android, do not modify.
 */


#ifndef JJK__tv_danmaku_ijk_media_player_misc_IMediaDataSource__H
#define JJK__tv_danmaku_ijk_media_player_misc_IMediaDataSource__H

#include "ijksdl/android/jjk/internal/jjk_internal.h"

jint JJKC_IMediaDataSource__readAt(JNIEnv *env, jobject thiz, jlong position, jbyteArray buffer, jint offset, jint size);
jint JJKC_IMediaDataSource__readAt__catchAll(JNIEnv *env, jobject thiz, jlong position, jbyteArray buffer, jint offset, jint size);
jlong JJKC_IMediaDataSource__getSize(JNIEnv *env, jobject thiz);
jlong JJKC_IMediaDataSource__getSize__catchAll(JNIEnv *env, jobject thiz);
void JJKC_IMediaDataSource__close(JNIEnv *env, jobject thiz);
void JJKC_IMediaDataSource__close__catchAll(JNIEnv *env, jobject thiz);
int JJK_loadClass__JJKC_IMediaDataSource(JNIEnv *env);

#define JJK_HAVE__JJKC_IMediaDataSource

#endif//JJK__tv_danmaku_ijk_media_player_misc_IMediaDataSource__H
