/*
 * Copyright (C) 2015 Zhang Rui <bbcallen@gmail.com>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * https://github.com/Bilibili/jni4android
 * This file is automatically generated by jni4android, do not modify.
 */

#ifndef J4A__test_ReturnPrimitive__H
#define J4A__test_ReturnPrimitive__H

#include "j4a/j4a_base.h"

jint J4AC_test_ReturnPrimitive__getIntArray(JNIEnv *env, jobject thiz, jintArray iArr);
jint J4AC_test_ReturnPrimitive__getIntArray__catchAll(JNIEnv *env, jobject thiz, jintArray iArr);
jfloat J4AC_test_ReturnPrimitive__getFloatArray(JNIEnv *env, jobject thiz, jfloatArray fArr);
jfloat J4AC_test_ReturnPrimitive__getFloatArray__catchAll(JNIEnv *env, jobject thiz, jfloatArray fArr);
jdouble J4AC_test_ReturnPrimitive__getDoubleArray(JNIEnv *env, jobject thiz, jdoubleArray iArr);
jdouble J4AC_test_ReturnPrimitive__getDoubleArray__catchAll(JNIEnv *env, jobject thiz, jdoubleArray iArr);
int J4A_loadClass__J4AC_test_ReturnPrimitive(JNIEnv *env);

#define J4A_HAVE_SIMPLE__J4AC_test_ReturnPrimitive

#define J4AC_ReturnPrimitive__getIntArray J4AC_test_ReturnPrimitive__getIntArray
#define J4AC_ReturnPrimitive__getIntArray__catchAll J4AC_test_ReturnPrimitive__getIntArray__catchAll
#define J4AC_ReturnPrimitive__getFloatArray J4AC_test_ReturnPrimitive__getFloatArray
#define J4AC_ReturnPrimitive__getFloatArray__catchAll J4AC_test_ReturnPrimitive__getFloatArray__catchAll
#define J4AC_ReturnPrimitive__getDoubleArray J4AC_test_ReturnPrimitive__getDoubleArray
#define J4AC_ReturnPrimitive__getDoubleArray__catchAll J4AC_test_ReturnPrimitive__getDoubleArray__catchAll
#define J4A_loadClass__J4AC_ReturnPrimitive J4A_loadClass__J4AC_test_ReturnPrimitive

#endif//J4A__test_ReturnPrimitive__H
