/*
 * Copyright (C) 2015 Zhang Rui <bbcallen@gmail.com>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * https://github.com/Bilibili/jni4android
 * This file is automatically generated by jni4android, do not modify.
 */


#ifndef JJK__java_util_ArrayList__H
#define JJK__java_util_ArrayList__H

#include "ijksdl/android/jjk/internal/jjk_internal.h"

jobject JJKC_ArrayList__ArrayList(JNIEnv *env);
jobject JJKC_ArrayList__ArrayList__catchAll(JNIEnv *env);
jobject JJKC_ArrayList__ArrayList__asGlobalRef__catchAll(JNIEnv *env);
jboolean JJKC_ArrayList__add(JNIEnv *env, jobject thiz, jobject object);
jboolean JJKC_ArrayList__add__catchAll(JNIEnv *env, jobject thiz, jobject object);
int JJK_loadClass__JJKC_ArrayList(JNIEnv *env);

#define JJK_HAVE__JJKC_ArrayList

#endif//JJK__java_util_ArrayList__H
