/*
 * Copyright (C) 2015 Zhang Rui <bbcallen@gmail.com>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * https://github.com/Bilibili/jni4android
 * This file is automatically generated by jni4android, do not modify.
 */


#ifndef JJK__java_nio_ByteBuffer__H
#define JJK__java_nio_ByteBuffer__H

#include "ijksdl/android/jjk/internal/jjk_internal.h"

jobject JJKC_ByteBuffer__allocate(JNIEnv *env, jint capacity);
jobject JJKC_ByteBuffer__allocate__catchAll(JNIEnv *env, jint capacity);
jobject JJKC_ByteBuffer__allocate__asGlobalRef__catchAll(JNIEnv *env, jint capacity);
jobject JJKC_ByteBuffer__allocateDirect(JNIEnv *env, jint capacity);
jobject JJKC_ByteBuffer__allocateDirect__catchAll(JNIEnv *env, jint capacity);
jobject JJKC_ByteBuffer__allocateDirect__asGlobalRef__catchAll(JNIEnv *env, jint capacity);
jobject JJKC_ByteBuffer__limit(JNIEnv *env, jobject thiz, jint newLimit);
jobject JJKC_ByteBuffer__limit__catchAll(JNIEnv *env, jobject thiz, jint newLimit);
jobject JJKC_ByteBuffer__limit__asGlobalRef__catchAll(JNIEnv *env, jobject thiz, jint newLimit);
int JJK_loadClass__JJKC_ByteBuffer(JNIEnv *env);

#define JJK_HAVE__JJKC_ByteBuffer

#include "ByteBuffer.util.h"

#endif//JJK__java_nio_ByteBuffer__H
