/*
 * copyright (c) 2015 Zhang Rui <bbcallen@gmail.com>
 *
 * This file is part of jni4android.
 *
 * jni4android is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * jni4android is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with jni4android; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA
 */

#include "ast_compilation_unit.hpp"

#include <fstream>
#include <iostream>
#include "ast_method.hpp"
#include "ast_class.hpp"
#include "ast__context.hpp"

using namespace ast;

static const char *J4A_LICENSE_HEADER =
"/*\n"
" * Copyright (C) 2015 Zhang Rui <bbcallen@gmail.com>\n"
" *\n"
" * Licensed under the Apache License, Version 2.0 (the \"License\");\n"
" * you may not use this file except in compliance with the License.\n"
" * You may obtain a copy of the License at\n"
" *\n"
" *      http://www.apache.org/licenses/LICENSE-2.0\n"
" *\n"
" * Unless required by applicable law or agreed to in writing, software\n"
" * distributed under the License is distributed on an \"AS IS\" BASIS,\n"
" * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.\n"
" * See the License for the specific language governing permissions and\n"
" * limitations under the License.\n"
" */\n"
"\n"
"/*\n"
" * https://github.com/Bilibili/jni4android\n"
" * This file is automatically generated by jni4android, do not modify.\n"
" */\n";

void CompilationUnit::do_build(
    std::ostream &h_os,
    std::ostream &c_os,
    std::ostream &j4a_include_stream,
    std::ostream &j4a_loader_stream)
{
    Class *clazz = get_clazz();

    printf("==========\n");
    // printf("%s\n", __func__);

    // .h
    h_os << J4A_LICENSE_HEADER << std::endl;
    h_os << "#ifndef " << get_header_macro() << std::endl;
    h_os << "#define " << get_header_macro() << std::endl;
    h_os << std::endl;
    h_os << "#include \"j4a/j4a_base.h\"" << std::endl;
    h_os << std::endl;

    clazz->build_c_func_decl(h_os);
    h_os << std::endl;
    if (clazz->need_c_simple_class_name()) {
        h_os << "#define J4A_HAVE_SIMPLE__" << clazz->get_c_class_name() << std::endl;
        h_os << std::endl;
        clazz->build_c_simple_func_decl(h_os);
        h_os << std::endl;
    }
    h_os << "#endif//" << get_header_macro() << std::endl;

    // .c
    c_os << J4A_LICENSE_HEADER << std::endl;
    c_os << "#include \"" << clazz->get_name() << ".h\"" << std::endl;

    clazz->build_c_class_decl(c_os);
    clazz->build_c_func_impl(c_os);

    // .include.j4a
    j4a_include_stream << "#include \"" << get_include_path() << "\"";

    // .loader.j4a
    j4a_loader_stream << "    J4A_LOAD_CLASS(" << clazz->get_c_class_name(false) << ");";
}

void CompilationUnit::build()
{
    std::ofstream h_stream;
    std::ofstream c_stream;
    std::ofstream j4a_include_stream;
    std::ofstream j4a_loader_stream;
    std::ostream *h_stream_ptr = &std::cout;
    std::ostream *c_stream_ptr = &std::cout;
    std::ostream *j4a_include_stream_ptr = &std::cout;
    std::ostream *j4a_loader_stream_ptr = &std::cout;

    if (!Context::instance()->get_h_file_path().empty()) {
        h_stream.open(Context::instance()->get_h_file_path().c_str());
        if (!h_stream.is_open()) {
            printf("failed to open output .h file %s\n", Context::instance()->get_h_file_path().c_str());
            return;
        }
        h_stream_ptr = &h_stream;
    }

    if (!Context::instance()->get_c_file_path().empty()) {
        c_stream.open(Context::instance()->get_c_file_path().c_str());
        if (!c_stream) {
            printf("failed to open output .c file %s\n", Context::instance()->get_c_file_path().c_str());
            return;
        }
        c_stream_ptr = &c_stream;
    }

    if (!Context::instance()->get_j4a_include_file_path().empty()) {
        j4a_include_stream.open(Context::instance()->get_j4a_include_file_path().c_str());
        if (!j4a_include_stream) {
            printf("failed to open output .include.j4a file %s\n", Context::instance()->get_j4a_include_file_path().c_str());
            return;
        }
        j4a_include_stream_ptr = &j4a_include_stream;
    }

    if (!Context::instance()->get_j4a_loader_file_path().empty()) {
        j4a_loader_stream.open(Context::instance()->get_j4a_loader_file_path().c_str());
        if (!j4a_loader_stream) {
            printf("failed to open output .loader.j4a file %s\n", Context::instance()->get_j4a_loader_file_path().c_str());
            return;
        }
        j4a_loader_stream_ptr = &j4a_loader_stream;
    }

    do_build(*h_stream_ptr, *c_stream_ptr, *j4a_include_stream_ptr, *j4a_loader_stream_ptr);
}
